version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-discovery
      dockerfile: Dockerfile
    container_name: eureka-discovery
    ports:
      - "8761:8761"
    networks:
      - eureka-network


  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
        - eureka-network

  user-service:
    build: ./user-service
    depends_on:
      - eureka-server
      - kafka
      - mysql
      -
  newsfeed-service:
    build: ./newsfeed-service
    depends_on:
      - eureka-server
      - kafka
      - mysql

  activity-service:
    build: ./activity-service
    depends_on:
      - eureka-server
      - kafka
      - mysql

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stocktalk
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"